version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.15.0-stretch

jobs:
  deps:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn run lint
  test:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn run test
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn run build
      - persist_to_workspace:
          root: .
          paths: dist
  publish:
    executor: node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish dist/router-store --access=public

workflows:
  version: 2.1
  default_workflow:
    jobs:
      - deps
      - lint:
          requires:
            - deps
      - test:
          requires:
            - deps
      - build:
          requires:
            - deps
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master
