version: 2
jobs:
  deps:
    docker:
      - image: circleci/node:10.15.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/node:10.15.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn run lint
  test:
    docker:
      - image: circleci/node:10.15.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn run test
  build:
    docker:
      - image: circleci/node:10.15.0-stretch
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: yarn run build
workflows:
  version: 2
  default_workflow:
    jobs:
      - deps
      - lint:
          requires:
            - deps
      - test:
          requires:
            - deps
      - build:
          requires:
            - deps
